import type { Metadata } from "next";
import { ReactNode } from "react";
import localFont from "next/font/local";

import "./globals.css";

// COMPONENTS
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/StairTransition";

const jetBrainMono = localFont({
  src: "../fonts/JetBrainsMono-Regular.ttf",
});

export const metadata: Metadata = {
  title: "Chidi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={` ${jetBrainMono.className} bg-[#1c1c22] text-white antialiased`}>
        <Header />
        <StairTransition />
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  );
}
